### PR TITLE
fix #98

### LINKED ISSUE #98: Syntax error in latest commit...
I am receiving the following error when attempting to initialize the latest BIM_Workbench commit in Freecad 0.20.1

00:32:20  invalid syntax (BimSetup.py, line 464)
00:32:20  Traceback (most recent call last):
  File "<string>", line 84, in Initialize
  File "/tmp/.mount_FreeCArviCMj/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)

### PR DESCRIPTION
**Pull request by htlcnn**
fix #98

### CODE REVIEW

**Comment by luzpaz** [comment]
@yorikvanhavre ping

**Comment by yorikvanhavre** [comment]
Doh :) thanks!!

**Comment by mado987** [comment]
extraordinary ! I really hope one day to be able to give my time to the community in such an effective way.

Thanks

**Comment by luzpaz** [comment]
@mado987 Don't wait too long. Coding is not the only way you can give time. :wink:

**Pull request merged**
