### PR TITLE
BIM Improved Library

### PR DESCRIPTION
**Pull request by Beton1**
Added the options to preview files in 3D mode and to link them to the main document(from which the library is opened). Also ported the save and preview options from the Part library macro and added the possibility to automaticaly save thumbnails when a file is clicked.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
sorry forgot to come look here.. this looks super good! i'm more or less in holidays this week, but i give it a test spin and merge ASAP!

**Comment by Beton1** [comment]
Great, thanks, cant wait to see it merged!

**Comment by yorikvanhavre** [comment]
Okay I finally found the time to review the code. Awfully sorry for the time it took :grimacing: Overall it's great! A couple of improvement I'd like though:
* Tooltips on the "Link" and "Save" buttons
* I think the save button should be renamed a s"Save as..." (or maybe "Add to library...") so the user knows a new dialog will open
* Either "Insert >>" should become "Insert", or "Link" should become "Link >>"
* All the print() statements in your code should be replaced by FreeCAD.Console.PrintMessage() or FreeCAD.Console.PrintWarning() or FreeCAD.Console.PrintError() and the text should be placed in a translate() function and "\n" should be added to it. Example:
`FreeCAD.Console.PrintError(translate("BIM","Please save the document first")+"\n")`
* I think the save button should go all the way to the bottom, below the search buttons, because it's a different kind of functionality than just "using" the library.
* It would be cool if the preview image would have a max width of the available column width, so if the task column is smaller than the image, it gets smaller to fit the space. I don't remember exactly how to do that, but it should be findable in QDesigner
* The open/closed state of the preview section should be remembered across sessions so when you use the tool again it is open if you left it open last time

Don't know if that's clear... If these make sense to you and you feel like working on some of those, we can leave this PR open and add commits to it, otherwise we keep this list as todo and do it (me or you or anybody else) in another PR

**Comment by Beton1** [comment]
Thank you for the response, really appreciate it :D I think I understood most of the points, I dont have so much time to fix them now, but when I find some time I will do it. And I totally understand, I hope you managed to get some rest, what you are doing for FreeCAD in general is really awesome :D

Sent from Yahoo Mail for iPad


On Wednesday, December 1, 2021, 12:12 PM, Yorik van Havre ***@***.***> wrote:




Okay I finally found the time to review the code. Awfully sorry for the time it took 😬 Overall it's great! A couple of improvement I'd like though:
   
   - Tooltips on the "Link" and "Save" buttons
   - I think the save button should be renamed a s"Save as..." (or maybe "Add to library...") so the user knows a new dialog will open
   - Either "Insert >>" should become "Insert", or "Link" should become "Link >>"
   - All the print() statements in your code should be replaced by FreeCAD.Console.PrintMessage() or FreeCAD.Console.PrintWarning() or FreeCAD.Console.PrintError() and the text should be placed in a translate() function and "\n" should be added to it. Example:   
FreeCAD.Console.PrintError(translate("BIM","Please save the document first")+"\n")
   - I think the save button should go all the way to the bottom, below the search buttons, because it's a different kind of functionality than just "using" the library.
   - It would be cool if the preview image would have a max width of the available column width, so if the task column is smaller than the image, it gets smaller to fit the space. I don't remember exactly how to do that, but it should be findable in QDesigner
   - The open/closed state of the preview section should be remembered across sessions so when you use the tool again it is open if you left it open last time

Don't know if that's clear... If these make sense to you and you feel like working on some of those, we can leave this PR open and add commits to it, otherwise we keep this list as todo and do it (me or you or anybody else) in another PR

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yorikvanhavre** [comment]
Ok then let's merge this already and keep the above list, I'll try to work on it too when I have a moment...

**Pull request merged**
